version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    healthcheck:
      test: "echo 'db.runCommand({ping: 1})' | mongo localhost:27017/test"
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - mongodb_data:/data/db
    networks:
      - internal_network

  flask-jwt:
    image: flask-jwt:v0.4
    env_file:
      - .env
    build:
      args:
        PYTHON_VERSION: 3.10.13
    ports:
      - "8000:8000"
    command: ["poetry", "run", "python", "-m", "gunicorn", "-w", "1", "run:app", "-b", "0.0.0.0:8000"]
    depends_on:
      - mongodb
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge

volumes:
  mongodb_data:
